#!/bin/bash
export BASEPKGS=(
 'neofetch' #necessary programs 
 'xdg-user-dirs'
 'python'
 'git'
 'qt6-wayland'
 'libgtk-3-dev'
 'sddm'
 'python'
 'python-pip'
 'os-prober'
 'traceroute' #network utils
 'nmap'
 'ufw'
 'iw'
 'iwd'
 'netctl'
 'dhcpcd'
 'dhclient'
 'networkmanager'
 'grub' #grub/boot 
 'grub-customizer' 
 'efibootmgr' 
 'which' #utils
 'wget' 
 'dialog'
 'util-linux' 
 'tree' 
 'unzip' 
 'xdg-user-dirs' 
 'exfat-utils'
 'gptfdisk'
 'openssh'
 'pacman-contrib'
 'qemu'
 'autoconf' # build
 'automake'
 'gcc'
 'zip'
 'terminus-font' # fonts
 'noto-fonts'
)

export GUIPKGS=(
 'sway' #desktop env
 'swaybg'
 'lxqt-policykit'
 'polkit-kde-agent'
 'i3-gaps'
 'megasync'
 'nano'
 'code'
 'archlinux-wallpaper'
 'pulseaudio'
 'pulseaudio-alsa'
 'pulseaudio-bluetooth' #bluetooth
 'thunar' #grapical utils
 'gparted'
 'alacritty'
 'vlc'
 'firefox'
 'steam'
 'obs-studio'
 'tldr'
 'flameshot'
 'cups' #printing
 'print-manager'
 'wine-gecko' #wine
 'wine-mono'
 'winetricks'
 'lutris'
 'rofi'
 'breeze'
 'qt5ct'
 'lxappearance'
)

export AURPKGS=(
 'spotify'
# 'nerd-fonts-complete'
 'cpupower-gui'
 'waybar'
 'dxvk-bin'
)
